# frozen_string_literal: true

require_relative "test_helper"

class ShellIntegrationTest < SpaceCadetTest
  def fish_script
    SpaceCadet::ShellIntegration.for("fish")
  end

  def test_for_fish_embeds_current_version
    assert_includes fish_script, SpaceCadet::VERSION
  end

  def test_for_fish_no_unresolved_placeholder
    refute_includes fish_script, "__SPACE_CADET_VERSION__"
  end

  def test_for_fish_preserves_literal_argv
    assert_includes fish_script, "$argv"
  end

  def test_for_fish_preserves_literal_color_args
    assert_includes fish_script, "--color=always $__space_args"
  end

  def test_for_fish_contains_version_check
    assert_includes fish_script, "--version"
  end

  def test_for_fish_stale_message_names_install_command
    assert_includes fish_script, "space shell fish install"
  end

  def test_for_fish_contains_managed_marker
    assert_includes fish_script, "Generated by space-cadet"
  end

  def test_for_fish_guard_uses_session_sentinel
    assert_includes fish_script, "__space_cadet_compat_checked"
  end

  def test_for_fish_guard_does_not_block
    # The space function must still call `command space` after the guard check.
    # Both branches of the switch must be present.
    assert_includes fish_script, "command space $__space_args"
  end

  def test_for_unsupported_shell_raises
    assert_raises(SpaceCadet::Error) { SpaceCadet::ShellIntegration.for("zsh") }
  end

  def test_managed_fish_recognizes_marker
    assert SpaceCadet::ShellIntegration.managed_fish?("# Generated by space-cadet. Do not edit by hand.\n")
  end

  def test_managed_fish_recognizes_function_names
    content = "function __space_cadet_command\nfunction space --wraps space"
    assert SpaceCadet::ShellIntegration.managed_fish?(content)
  end

  def test_managed_fish_rejects_unmanaged
    refute SpaceCadet::ShellIntegration.managed_fish?("function space\n  echo hello\nend\n")
  end

  def test_install_unchanged_when_same_content
    tmp = temp_env
    result = SpaceCadet::ShellIntegration.install("fish", env: tmp[:env])
    assert_equal :installed, result.fetch(:action)

    result2 = SpaceCadet::ShellIntegration.install("fish", env: tmp[:env])
    assert_equal :unchanged, result2.fetch(:action)
  ensure
    FileUtils.rm_rf(tmp[:root]) if tmp
  end

  def test_install_updated_when_content_changes
    tmp = temp_env
    path = SpaceCadet::ShellIntegration.path_for("fish", env: tmp[:env])
    FileUtils.mkdir_p(path.dirname)
    path.write("# Generated by space-cadet. Do not edit by hand.\nold content\n")

    result = SpaceCadet::ShellIntegration.install("fish", env: tmp[:env])
    assert_equal :updated, result.fetch(:action)
  ensure
    FileUtils.rm_rf(tmp[:root]) if tmp
  end

  def test_install_raises_on_unmanaged_without_force
    tmp = temp_env
    path = SpaceCadet::ShellIntegration.path_for("fish", env: tmp[:env])
    FileUtils.mkdir_p(path.dirname)
    path.write("function space\n  echo hello\nend\n")

    assert_raises(SpaceCadet::Error) do
      SpaceCadet::ShellIntegration.install("fish", env: tmp[:env])
    end
  ensure
    FileUtils.rm_rf(tmp[:root]) if tmp
  end
end
