# frozen_string_literal: true

module Space
  module Server
    module Operations
      # Renders a pi provider extension (BRIEF §4.6) from a provider row + its
      # live model list — retiring the operator's hand-maintained
      # local-inference.ts for provider rows managed through the app (that file
      # remains valid as a profile file). Pure render, no I/O: the caller
      # (Actions::Providers::PiExtension) owns fetching the model list.
      #
      # §2.4 secret hygiene is load-bearing here: this operation never sees or
      # embeds a resolved secret, and never embeds the op:// ref itself — a
      # key-bearing provider gets a `process.env.PI_PROVIDER_API_KEY`
      # indirection that the executor's existing secret transport (bare `-e
      # NAME`, see SandboxArgv) materializes at sandbox runtime.
      class GeneratePiExtension
        EXTENSIONS_DIR = "/root/.pi/agent/extensions"
        ENV_KEY = "PI_PROVIDER_API_KEY"
        CONTEXT_WINDOW = 131_072
        MAX_TOKENS = 32_768

        # => { path:, content:, env_key: }
        def call(provider, model_ids)
          slug = slugify(provider.name)
          {
            path: "#{EXTENSIONS_DIR}/#{slug}.ts",
            content: render(provider, slug, model_ids),
            env_key: provider.api_key_ref ? ENV_KEY : nil
          }
        end

        private

        def slugify(name)
          name.to_s.downcase.gsub(/[^a-z0-9]+/, "-").gsub(/\A-+|-+\z/, "")
        end

        def render(provider, slug, model_ids)
          <<~TS
            // Generated by space-architect for provider "#{provider.name}" (BRIEF I25 §4.6).
            // Conservative defaults: reasoning/contextWindow/maxTokens/compat are generic
            // for every model — hand-tuned extensions (e.g. local-inference.ts) remain
            // valid as profile files.
            #{api_key_comment(provider)}

            import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

            export default function (pi: ExtensionAPI) {
              pi.registerProvider("#{slug}", {
                name: #{provider.name.to_s.inspect},
                baseUrl: #{"#{provider.base_url}/v1".inspect},
                apiKey: #{api_key_expr(provider)},
                api: "openai-completions",
                models: [
            #{model_entries(model_ids)}
                ],
              });
            }
          TS
        end

        def api_key_comment(provider)
          if provider.api_key_ref
            "// Key-bearing provider: apiKey resolves from the sandbox's PI_PROVIDER_API_KEY env var at runtime."
          else
            "// Keyless provider: apiKey is a documented dummy (pi requires the field syntactically)."
          end
        end

        def api_key_expr(provider)
          provider.api_key_ref ? 'process.env.PI_PROVIDER_API_KEY ?? "unset"' : '"local-proxy"'
        end

        def model_entries(model_ids)
          model_ids.map { |id| model_entry(id) }.join("\n")
        end

        def model_entry(id)
          lines = [
            "    {",
            "      id: #{id.to_s.inspect},",
            "      name: #{id.to_s.inspect},",
            "      reasoning: true,",
            "      input: [\"text\"],",
            "      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },",
            "      contextWindow: #{CONTEXT_WINDOW},",
            "      maxTokens: #{MAX_TOKENS},",
            "      compat: {",
            "        supportsDeveloperRole: false,",
            "        supportsReasoningEffort: false,",
            "      },",
            "    },"
          ]
          lines.join("\n")
        end
      end
    end
  end
end
