# frozen_string_literal: true

require "space_src"

require_relative "space_architect/version"
require_relative "space_architect/errors"
require_relative "space_architect/warnings"
SpaceArchitect::Warnings.disable_experimental!
require_relative "space_architect/atomic_write"
require_relative "space_architect/xdg"
require_relative "space_architect/config"
require_relative "space_architect/state"
require_relative "space_architect/slugger"
require_relative "space_architect/space"
require_relative "space_architect/repo_reference"
require_relative "space_architect/repo_resolver"
require_relative "space_architect/git_client"
require_relative "space_architect/mise_client"
require_relative "space_architect/space_store"
require_relative "space_architect/shell_integration"
require_relative "space_architect/terminal"
require_relative "space_architect/harness"
require_relative "space_architect/dispatcher"
require_relative "space_architect/architect_mission"
require_relative "space_architect/cli"
