FROM <%= base_image %>
<% if deps.any? -%>

RUN apt-get update -qq \
 && apt-get install -y --no-install-recommends \
      <%= deps.join(" \\\n      ") %> \
 && rm -rf /var/lib/apt/lists/*
<% end -%>
<% if npm.any? -%>

RUN npm install -g \
      <%= npm.join(" \\\n      ") %>
<% end -%>
<% files.each_with_index do |f, i| -%>

COPY files/<%= i %> <%= f[:path] %>
<% end -%>
