# frozen_string_literal: true

module Space::Src
  # Generates the standalone `src` fish shell integration.
  module ShellIntegration
    FISH_TEMPLATE = <<~'FISH'
      # Generated by space-src. Do not edit by hand.

      function src --wraps src --description "Navigate source checkouts"
          switch "$argv[1]"
              case repo org sync status config daemon clone shell
                  command src $argv
                  return $status
              case '*'
                  set -l __src_output (command src $argv)
                  set -l __src_status $status

                  if test (count $__src_output) -gt 0
                      printf "%s\n" $__src_output
                  end

                  if test $__src_status -eq 0
                      set -l __src_target $__src_output[-1]
                      set __src_target (string replace -r "^~(?=/|$)" $HOME -- $__src_target)
                      if test -d "$__src_target"
                          cd "$__src_target"
                      end
                  end

                  return $__src_status
          end
      end
    FISH

    def self.for(shell)
      case shell.to_s
      when "fish"
        FISH_TEMPLATE
      else
        raise "Unsupported shell '#{shell}'. Expected: fish"
      end
    end
  end
end
