--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: annotations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.annotations (
    id bigint NOT NULL,
    anchor_message_id bigint,
    body text NOT NULL,
    conversation_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    selector jsonb,
    target_kind text NOT NULL,
    tool_use_id text,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: annotations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.annotations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.annotations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: artifacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.artifacts (
    id bigint NOT NULL,
    space_id bigint NOT NULL,
    iteration_id bigint,
    kind text NOT NULL,
    path text NOT NULL,
    title text,
    raw text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: artifacts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.artifacts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.artifacts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conversation_shares; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversation_shares (
    id bigint NOT NULL,
    access text DEFAULT 'view'::text NOT NULL,
    conversation_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    github_id text NOT NULL,
    github_login text NOT NULL,
    grantee_kind text NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: conversation_shares_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conversation_shares ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversation_shares_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: conversations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.conversations (
    id bigint NOT NULL,
    agent_version text,
    created_at timestamp with time zone NOT NULL,
    git_branch text,
    original_cwd text,
    published boolean DEFAULT false NOT NULL,
    session_id text,
    source text,
    status integer DEFAULT 0 NOT NULL,
    title text,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    source_file_data text
);


--
-- Name: conversations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.conversations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.conversations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: iterations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.iterations (
    id bigint NOT NULL,
    space_id bigint NOT NULL,
    ordinal integer NOT NULL,
    name text NOT NULL,
    slug text,
    freeze_sha text,
    verdict text,
    status text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    occurred_at timestamp with time zone,
    occurred_at_utc_offset integer
);


--
-- Name: iterations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.iterations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.iterations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.jobs (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    spec jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text DEFAULT 'queued'::text NOT NULL,
    run_id bigint,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    leased_until timestamp with time zone,
    attempts integer DEFAULT 0 NOT NULL,
    failure_evidence text,
    CONSTRAINT jobs_status_check CHECK ((status = ANY (ARRAY['queued'::text, 'running'::text, 'succeeded'::text, 'failed'::text, 'canceled'::text])))
);


--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.messages (
    id bigint NOT NULL,
    content jsonb DEFAULT '[]'::jsonb NOT NULL,
    conversation_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    model text,
    occurred_at timestamp with time zone,
    parent_uuid text,
    "position" integer NOT NULL,
    published boolean DEFAULT false NOT NULL,
    role text NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    uuid text
);


--
-- Name: messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    name text NOT NULL,
    harness_type text NOT NULL,
    spec jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    provider_id bigint
);


--
-- Name: profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.providers (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    name text NOT NULL,
    base_url text NOT NULL,
    api_key_ref text,
    flavors jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: providers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.runs (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    status integer DEFAULT 0 NOT NULL,
    producer text,
    session_id text,
    published boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    conversation_id bigint,
    space_id bigint,
    iteration_id bigint,
    lane text,
    role text DEFAULT 'builder'::text NOT NULL,
    occurred_at timestamp with time zone,
    harness text,
    model text
);


--
-- Name: runs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.runs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


--
-- Name: spaces; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.spaces (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    slug text NOT NULL,
    title text,
    status text,
    source_path text,
    repos jsonb DEFAULT '[]'::jsonb,
    imported_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    git_utc_offset integer
);


--
-- Name: spaces_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.spaces ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spaces_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    avatar_url text,
    created_at timestamp with time zone NOT NULL,
    email text,
    github_orgs jsonb DEFAULT '[]'::jsonb NOT NULL,
    github_uid text NOT NULL,
    name text,
    orgs_synced_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL,
    username text NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: annotations annotations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotations
    ADD CONSTRAINT annotations_pkey PRIMARY KEY (id);


--
-- Name: artifacts artifacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_pkey PRIMARY KEY (id);


--
-- Name: conversation_shares conversation_shares_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_shares
    ADD CONSTRAINT conversation_shares_pkey PRIMARY KEY (id);


--
-- Name: conversations conversations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_pkey PRIMARY KEY (id);


--
-- Name: iterations iterations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.iterations
    ADD CONSTRAINT iterations_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: providers providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_pkey PRIMARY KEY (id);


--
-- Name: runs runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: spaces spaces_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.spaces
    ADD CONSTRAINT spaces_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: index_annotations_on_anchor_message_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_annotations_on_anchor_message_id ON public.annotations USING btree (anchor_message_id);


--
-- Name: index_annotations_on_conversation_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_annotations_on_conversation_id ON public.annotations USING btree (conversation_id);


--
-- Name: index_annotations_on_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_annotations_on_user_id ON public.annotations USING btree (user_id);


--
-- Name: index_artifacts_on_space_id_and_path; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_artifacts_on_space_id_and_path ON public.artifacts USING btree (space_id, path);


--
-- Name: index_conversation_shares_on_conversation_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_conversation_shares_on_conversation_id ON public.conversation_shares USING btree (conversation_id);


--
-- Name: index_conversation_shares_on_grantee_kind_and_github_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_conversation_shares_on_grantee_kind_and_github_id ON public.conversation_shares USING btree (grantee_kind, github_id);


--
-- Name: index_conversation_shares_unique_grantee; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_conversation_shares_unique_grantee ON public.conversation_shares USING btree (conversation_id, grantee_kind, lower(github_login));


--
-- Name: index_conversations_on_published; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_conversations_on_published ON public.conversations USING btree (published);


--
-- Name: index_conversations_on_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_conversations_on_session_id ON public.conversations USING btree (session_id);


--
-- Name: index_conversations_on_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_conversations_on_user_id ON public.conversations USING btree (user_id);


--
-- Name: index_iterations_on_space_id_and_ordinal; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_iterations_on_space_id_and_ordinal ON public.iterations USING btree (space_id, ordinal);


--
-- Name: index_jobs_on_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_jobs_on_status ON public.jobs USING btree (status);


--
-- Name: index_jobs_on_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_jobs_on_user_id ON public.jobs USING btree (user_id);


--
-- Name: index_jobs_queued_on_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_jobs_queued_on_created_at ON public.jobs USING btree (created_at) WHERE (status = 'queued'::text);


--
-- Name: index_jobs_running_on_leased_until; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_jobs_running_on_leased_until ON public.jobs USING btree (leased_until) WHERE (status = 'running'::text);


--
-- Name: index_messages_on_conversation_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_messages_on_conversation_id ON public.messages USING btree (conversation_id);


--
-- Name: index_messages_on_conversation_id_and_position; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_messages_on_conversation_id_and_position ON public.messages USING btree (conversation_id, "position");


--
-- Name: index_messages_on_conversation_id_and_uuid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_messages_on_conversation_id_and_uuid ON public.messages USING btree (conversation_id, uuid);


--
-- Name: index_messages_on_published; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_messages_on_published ON public.messages USING btree (published);


--
-- Name: index_profiles_on_provider_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_profiles_on_provider_id ON public.profiles USING btree (provider_id);


--
-- Name: index_profiles_on_user_id_and_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_profiles_on_user_id_and_name ON public.profiles USING btree (user_id, name);


--
-- Name: index_providers_on_user_id_and_name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_providers_on_user_id_and_name ON public.providers USING btree (user_id, name);


--
-- Name: index_runs_on_conversation_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_runs_on_conversation_id ON public.runs USING btree (conversation_id);


--
-- Name: index_runs_on_iteration_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_runs_on_iteration_id ON public.runs USING btree (iteration_id);


--
-- Name: index_runs_on_published; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_runs_on_published ON public.runs USING btree (published);


--
-- Name: index_runs_on_session_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_runs_on_session_id ON public.runs USING btree (session_id);


--
-- Name: index_runs_on_space_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_runs_on_space_id ON public.runs USING btree (space_id);


--
-- Name: index_runs_on_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX index_runs_on_user_id ON public.runs USING btree (user_id);


--
-- Name: index_spaces_on_user_id_and_slug; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_spaces_on_user_id_and_slug ON public.spaces USING btree (user_id, slug);


--
-- Name: index_users_on_github_uid; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX index_users_on_github_uid ON public.users USING btree (github_uid);


--
-- Name: annotations annotations_anchor_message_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotations
    ADD CONSTRAINT annotations_anchor_message_id_fkey FOREIGN KEY (anchor_message_id) REFERENCES public.messages(id);


--
-- Name: annotations annotations_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotations
    ADD CONSTRAINT annotations_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id);


--
-- Name: annotations annotations_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.annotations
    ADD CONSTRAINT annotations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: artifacts artifacts_iteration_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_iteration_id_fkey FOREIGN KEY (iteration_id) REFERENCES public.iterations(id) ON DELETE SET NULL;


--
-- Name: artifacts artifacts_space_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.spaces(id) ON DELETE CASCADE;


--
-- Name: conversation_shares conversation_shares_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversation_shares
    ADD CONSTRAINT conversation_shares_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id);


--
-- Name: conversations conversations_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.conversations
    ADD CONSTRAINT conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: iterations iterations_space_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.iterations
    ADD CONSTRAINT iterations_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.spaces(id) ON DELETE CASCADE;


--
-- Name: jobs jobs_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE SET NULL;


--
-- Name: jobs jobs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: messages messages_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id);


--
-- Name: profiles profiles_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id) ON DELETE SET NULL;


--
-- Name: profiles profiles_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: providers providers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.providers
    ADD CONSTRAINT providers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: runs runs_conversation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id) ON DELETE SET NULL;


--
-- Name: runs runs_iteration_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_iteration_id_fkey FOREIGN KEY (iteration_id) REFERENCES public.iterations(id) ON DELETE SET NULL;


--
-- Name: runs runs_space_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_space_id_fkey FOREIGN KEY (space_id) REFERENCES public.spaces(id) ON DELETE SET NULL;


--
-- Name: runs runs_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.runs
    ADD CONSTRAINT runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: spaces spaces_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.spaces
    ADD CONSTRAINT spaces_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


SET search_path TO "$user", public;

INSERT INTO schema_migrations (filename) VALUES
('20260614000000_create_domain_tables.rb'),
('20260617000000_add_source_file_data_to_conversations.rb'),
('20260622000000_create_runs.rb'),
('20260623000000_add_conversation_id_to_runs.rb'),
('20260627120000_create_space_tables.rb'),
('20260628000000_add_occurred_at_to_runs_and_iterations.rb'),
('20260629000000_add_utc_offset_columns.rb'),
('20260630000000_add_harness_model_to_runs.rb'),
('20260701000000_create_jobs.rb'),
('20260718000000_add_lease_to_jobs.rb'),
('20260719000000_add_failure_evidence_to_jobs.rb'),
('20260719010000_create_profiles.rb'),
('20260719020000_create_providers.rb'),
('20260719030000_add_provider_id_to_profiles.rb');
